---
- name: Install ACL on RedHat Based OS
  become: yes
  become_method: sudo
  yum:
    name: acl
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install ACL on Debian Based OS
  become: yes
  become_method: sudo
  apt:
    name: acl
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"
