---
- name: Install dnsutils package in Debain Based OS
  become: yes
  become_method: sudo
  apt:
    name: dnsutils
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install dnsutils package in RedHat Based OS
  become: yes
  become_method: sudo  
  yum:
    name: bind-utils
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"
