---
- name: Install tmux and htop using apt
  become: yes
  become_method: sudo
  apt:
    name:
      - tmux
      - htop
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install tmux and htop using yum
  become: yes
  become_method: sudo
  yum:
    name:
      - tmux
      - htop
    state: latest
    update_cache: true
  when: ansible_os_family == "RedHat"
