---
- name: Update the Packages
  import_tasks: update.yml

- name: Install Yum Utils
  become: yes
  become_method: sudo
  yum:
    name: yum-utils
    state: latest

- name: Check if Docker GPG Key is present
  become: yes
  become_method: sudo
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: dockerrepo

- name: Add the Docker Repository
  become: yes
  become_method: sudo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: not dockerrepo.stat.exists

- name: Install the Docker Packages
  become: yes
  become_method: sudo
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: Add the user to Docker Group
  become: yes
  become_method: sudo
  user:
    name: kali
    groups: docker
    append: yes

- name: Start and Enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes
