---
- name: Update and Upgrade using apt
  become: true
  become_method: sudo
  apt:
    update_cache: true
    upgrade: yes
  when: ansible_os_family == "Debian"

- name: Update and Upgrade using yum
  become: yes
  become_method: sudo
  yum:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_os_family == "RedHat"
