---
- name: Pull jq Docker Image
  become: yes
  become_method: sudo
  docker_image:
    name: ghcr.io/jqlang/jq:1.7.1 
    source: pull

- name: Add alias for the Jq container
  become: yes
  become_user: kali
  become_method: sudo
  lineinfile:
    path: ~/.bashrc
    line: 'alias jq="docker run -i ghcr.io/jqlang/jq"'
