---
- name: Install Waybackurls
  become: yes
  become_user: kali
  become_method: sudo 
  command: /usr/local/go/bin/go install github.com/tomnomnom/waybackurls@latest

- name: Install anew
  become: yes
  become_user: kali
  become_method: sudo 
  command: /usr/local/go/bin/go install -v github.com/tomnomnom/anew@latest


- name: Install Gobuster
  become: yes
  become_user: kali
  become_method: sudo
  command: /usr/local/go/bin/go install github.com/OJ/gobuster/v3@latest

- name: Install Subfinder
  become: yes
  become_user: kali
  become_method: sudo
  command: /usr/local/go/bin/go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest

- name: Install Httpx
  become: yes
  become_user: kali
  become_method: sudo
  command: /usr/local/go/bin/go install github.com/projectdiscovery/httpx/cmd/httpx@latest
