---
- name: Install Go Tools
  become: yes
  become_user: kali
  become_method: sudo 
  command: /usr/local/go/bin/go install "{{ item }}"
  loop:
    - github.com/tomnomnom/waybackurls@latest
    - github.com/tomnomnom/anew@latest
    - github.com/OJ/gobuster/v3@latest
    - github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
    - github.com/projectdiscovery/httpx/cmd/httpx@latest
