---
- name: Install nmap on RedHat based OS
  become: yes
  become_method: sudo
  yum:
    name: nmap
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install nmap on Debian Based OS
  become: yes
  become_method: sudo
  apt:
    name: nmap
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"
